version: '3.3'

services:
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "4290:9090"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  node-exporter:
    container_name: exporter
    hostname: exporter
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "4291:9100"
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  blackbox-exporter:
    hostname: blackbox-exporter
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox/:/config/
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped
    ports:
        - "4215:9115"
    networks:
      - default

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - "4230:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default


# latest alert manager not support api v1      
#  alertmanager:
#    container_name: alertmanager
#    hostname: alertmanager
#    image: prom/alertmanager:latest
#    user: root
#    ports:
#      - "127.0.0.1:9093:9093"
#    volumes:
#      - ./alertmanager/:/etc/alertmanager/
#    environment:
#      TZ: "Europe/Moscow"
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/etc/alertmanager/data'
#    restart: unless-stopped
#    networks:
#      - default

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
#    image: prom/alertmanager:v0.16.0
    image: prom/alertmanager:latest
    user: root
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    environment:
      TZ: "Europe/Moscow"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    restart: unless-stopped
    networks:
      - default

  alertmanager-bot:
    container_name: alertmanager-bot
    hostname: alertmanager-bot
    image: metalmatze/alertmanager-bot:latest
    user: root
    ports:
      - '8080:8080'
    volumes:
      - ./alertmanager-bot/data:/data
    command:
      - '--alertmanager.url=http://alertmanager:9093'
      - '--log.level=debug'
      - '--store=bolt'
      - '--bolt.path=/data/bot.db'
      - '--telegram.admin=${TELEGRAM_ADMIN}'
      - '--telegram.token=${TELEGRAM_TOKEN}'
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  karma:
    container_name: karma
    hostname: karma
    image: ubuntu/karma:0.120-22.04_stable
#    image: ghcr.io/prymitive/karma
    environment:
      CONFIG_FILE: /config.yml
      TZ: "Europe/Moscow"
    restart: unless-stopped
    ports:
      - "4280:8080"
    volumes:
      - ./karma/config.yml:/config.yml
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.28.0/24
