scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox-icmp'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ icmp ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-icmp.yml

  - job_name: 'blackbox-http'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-http.yml

  - job_name: 'blackbox-tcp'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ tcp_connect ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-tcp.yml