global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox-icmp'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ icmp ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-icmp.yml

  - job_name: 'blackbox-http'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-http.yml

  - job_name: 'blackbox-tcp'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [ tcp_connect ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.d/blackbox-tcp.yml

  - job_name: 'flussonic_server'
    scheme: https
    metrics_path: /streamer/api/v3/config
    basic_auth:
      username: 'username'
      password: 'password'
    params:
      format: [ openmetrics ]
    static_configs:
      - targets: [ 'example.com:443' ]

  - job_name: 'flussonic_streams'
    scheme: https
    metrics_path: /streamer/api/v3/streams
    basic_auth:
      username: 'username'
      password: 'password'
    params:
      format: [ openmetrics ]
    static_configs:
      - targets: [ 'example.com:443' ]
